### ISSUE TITLE
frame.copy()

### ISSUE THREAD

**Issue by muy123** [davesuketu215/Image_By_Fingertip_Trace#1]
File "main.py", line 175, in main
    clone, region_of_trace, gray = preprocess_frame(camera)
  File "main.py", line 64, in preprocess_frame
    clone = frame.copy();
AttributeError: 'NoneType' object has no attribute 'copy'

please help to resolve the above issue.

**Comment by davesuketu215** [comment]
Hi muy123,
Could you please let me know whether your webcam is able to turn ON and get the video input stream?

**Comment by muy123** [comment]
no, it is not

**Comment by davesuketu215** [comment]
Are you using Mac OS? In case you are using Mac OS, kindly change the code line as below:
main.py Line 283:
From     camera = cv2.VideoCapture(0, cv2.CAP_DSHOW)
To     camera = cv2.VideoCapture(0)

Because this is a frequent issue encountered with Mac OS, but works well on Windows.

Kindly verify and let me know.

**Comment by muy123** [comment]
I am using ubuntu 20.04 and it solves the problem for ubuntu too.
Thank you, sir
